### ISSUE TITLE
TC2 Aiming

### ISSUE THREAD

**Issue by SatoshiKunXD** [Stefanuk12/Aiming#10]
**Describe the bug**
Silent Aim doesn't work and prevents me from dealing damage even up close.

**To Reproduce**
1. Go to '[...](https://www.roblox.com/games/328028363/Typical-Colors-2)'

2. Click on '
Visibility Check On'
Enabled On
Fov 60
(Tested with everything listed) Target Part: HumanoidRootPart, Head, HeadHB, Hitbox
Silent Aim On
Toggle Mode On
Focus Mode Off 

3. Scroll down to 'None'

4. No errors from Synapse Console or Dev Console

**Expected behavior**
Silent Aim Working like v1

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac] Windows 64-Bit
 - Executor [e.g. Synapse X, ScriptWare] Synapse X
 - Executor Version [e.g. 1.0.0] v2.18.2

**Additional context**
A brief background. I've been using the first Universal Aimbot Released by [veriias](https://github.com/Averiias) and it's working wonders with the Raycast method (although very laggy). I tested this version using the sample (made sure to test it with all the methods as well because Raycast didn't work on this one) but upon several tries it just doesn't work and I can't deal damage to anything even when face to face.

**Comment by Stefanuk12** [comment]
What game is this on?

**Comment by SatoshiKunXD** [comment]
> What game is this on?

Typical Colors 2. I linked it at number 1 but for some reason it only hyperlinked the ellipses.

**Comment by Stefanuk12** [comment]
I tried using Raycast method. The silent aim does not work but my bullets do damage.

**Comment by SatoshiKunXD** [comment]
That's weird. From all my tries it just doesn't register even when I'm face to face with someone.

Is there a possibility that the silent aim will work for it? I'm currently using v1 but it's extremely laggy specially with visibility check.
