### ISSUE TITLE
camelCase variations of functions aren't checked

### ISSUE THREAD

**Issue by ghost** [Stefanuk12/Aiming#3]
this is kind of nitpicking but, you should check the camelCase variations of ray-casting functions, as some game developers use them. 

examples: 
workspace:raycast, workspace:findPartOnRayWithIgnoreList

**Comment by Stefanuk12** [comment]
Good shout, I'll add support for checking for these. I didn't know they actually existed lol.

**Comment by Stefanuk12** [comment]
Okay, I've added a system to work around this.
