### ISSUE TITLE
crashes/freezes and silent aim not working

### ISSUE THREAD

**Issue by killerof9ods** [Stefanuk12/Aiming#6]
**Describe the bug**
the silent doesn't work on crim maybe it's a config issue but like half the damn games I used you're old silent aim it don't work either crashes/freezes my game 

**To Reproduce**
1. Go to ' none'
2. Click on 'none'
3. Scroll down to 'none'
4. 
![image](https://user-images.githubusercontent.com/105953392/179813611-2d46ae1e-9c95-4d17-b709-075a8872a083.png)

**Expected behavior**
I expected the silent aim to work on half the games that you're other one worked on and it doesn't such as criminality  IR etc many other games to much to name 

**Screenshots**
![image](https://user-images.githubusercontent.com/105953392/179813663-b0b1d2ed-984c-45e7-bbea-467e4fa0a46c.png)

**Desktop (please complete the following information):**
 - OS: win 10 1909
 - Executor synapse X
 - Executor Version v2.17.0

**Additional context**

**Comment by Stefanuk12** [comment]
What silent aim method were you using?

**Comment by killerof9ods** [comment]
> 

all i go one by one or just turn on all

**Comment by Stefanuk12** [comment]
it might be the case that it's detected

**Comment by killerof9ods** [comment]
> it might be the case that it's detected

doubt it's detected lol even small games that have little to no anticheats?

**Comment by killerof9ods** [comment]
> it might be the case that it's detected

well is there anyway to fix this or what

**Comment by killerof9ods** [comment]
![image](https://user-images.githubusercontent.com/105953392/179867890-4d33c922-012a-4e58-9779-db836f414f89.png)

**Comment by killerof9ods** [comment]
![image](https://user-images.githubusercontent.com/105953392/179872255-f6b533a1-260d-4e06-b1d8-c58eefd9dbb7.png)

**Comment by killerof9ods** [comment]
![image](https://user-images.githubusercontent.com/105953392/179872401-d3096122-f338-40cb-a3ef-1c07c32294be.png)
vs old one works on alot more games this new version seems to perform worse hopefully you can fix all these bugs so it can be just as good as the other aimbot u made

**Comment by Xeon-E** [comment]
Stefan, use the original UI in my opinion, I know the venyx ui gets you bricked up but for a silent aim linoria or bracket fits much better. And when yours I hate having to scroll so much i cant find shit

**Comment by Stefanuk12** [comment]
lol just saw your comment. yeah i converted it to linoria, how is it?

**Comment by Stefanuk12** [comment]
Can you give more examples of games and the method used?
