### ISSUE TITLE
detected

### ISSUE THREAD

**Issue by aydynx** [Stefanuk12/Aiming#8]
got banned on an alt on dh customs and hood duels using silent, also the silent doesn’t aim onto all parts i put in the list only head and humanoidrootpart

**Comment by Stefanuk12** [comment]
not all games are supported. the game you listed has an anti cheat so you need a stand alone silent aim.

about targeting all parts, if you set TargetPart to "All", it should do that. currently it's not in the GUI so i'll add that soon

**Comment by aydynx** [comment]
i used just silent and got banned, and i was using “All” targets parts, even lists that contain multiple parts do not work

**Comment by Stefanuk12** [comment]
does it work with averiias's version?

**Comment by aydynx** [comment]
nope, i believe it could be fixed with a check to find the closest part to the player
